apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-pv-claim
    name: frontend
  name: mysql-pv-claim
  namespace: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: nfs-storage
